--CREATE TABLE IF NOT EXISTS ksiazki (
  --  id SERIAL PRIMARY KEY,
    --title VARCHAR(255)
--);
-- ALTER TABLE IF NOT EXISTS public.ksiazki ADD COLUMN author VARCHAR(255);
--ALTER TABLE IF NOT EXISTS public.ksiazki ADD COLUMN isbn VARCHAR(255);
--ALTER TABLE IF NOT EXISTS public.ksiazki ADD COLUMN year INTEGER;

